### ISSUE TITLE
Create a "real-world" E2E sample

### ISSUE THREAD

**Issue by pklaschka** [AdobeDocs/cc-libraries-api-samples#8]
Right now (which is also good), all samples are very "sandbox"-style (i.e., they are samples demonstrating the use of the APIs in an environment that's "stripped down" to only fit the purpose of building a sample for CC Library APIs, as compared to a sample for integrating the APIs into a real-world project).

It is difficult to find a good balance between the two, but I think it would be beneficial if we had at least one more "end to end complete". I.e., a sample that's not so complex that we can't maintain it anymore, but a sample that feels like it "integrates the APIs into a product" instead of something that "builds a product to test the APIs".

Some ideas (just as food for thought and to get a sense of the general scope I'm talking about):
- A NodeJS app that I could deploy to a company server where I can select an image from my Libraries and then download a "web-optimised", minimised (by the server, e.g., via a TinyPNG API or something similar) rendition in a specific resolution
- A browser extension that scans a website's CSS for color codes and adds them to a library
- (more on the gadget-y side of things 😜 ) a small NodeJS server that runs on my server and connects to some sort of network based lamp in my home (maybe something like Philips Hue) to a random (/last added/...) color from my libraries every X minutes

These ideas probably aren't so big that it's difficult to develop them in a short amount of time or maintain them, but solve a real (more or less) problem using the APIs, i.e., demonstrate using the APIs on a "real world" project. Something like this, I think, could be good so that developers may even find it useful for themselves (so they just install it) and then can begin to tinker with it 😉

**Comment by ashikka** [comment]
@pklaschka I"d like to work on this. Can you assign me this issue?
